<?php
// $Id$

/**
 * @file
 * Install file of the revenue_sharing_basic module
 */

/**
 * Implementation of hook_uninstall().
 */
function revenue_sharing_basic_uninstall() {
  variable_del('revenue_sharing_basic_client_id_profile_field');
  variable_del('revenue_sharing_basic_percentage_author');
  variable_del('revenue_sharing_basic_percentage_refer');
  variable_del('revenue_sharing_basic_revenue_enable');
}
