<?php

/**
 * @file
 * Install file of the revenue_sharing_basic module.
 */

/**
 * Implements hook_requirements().
 */
function revenue_sharing_basic_requirements($phase) {
  $requirements = array();
  $t = get_t();
  switch ($phase) {
    // At runtime, make sure that we have a publisher ID.
    case 'runtime':
      // TODO This variable was probably removed in Backdrop without replacement.
      if (config_get('system.performance', 'cache') && (variable_get('adsense_id_module', ADSENSE_ID_MODULE_DEFAULT) == 'revenue_sharing_basic_adsense')) {
        $requirements['revenue_sharing_nocache'] = array(
          'title' => $t('Revenue Sharing'),
          'value' => $t('Backdrop page cache is enabled.'),
          'description' => $t('This causes conflicts with revenue sharing, since the pages are stored in the cache and are not dynamically generated. If you experience issues with revenue sharing, then disable the page cache.'),
          'severity' => REQUIREMENT_WARNING,
        );
      }
      break;
  }
  return $requirements;
}

/**
 * Implements hook_uninstall().
 */
function revenue_sharing_basic_uninstall() {
  config_clear('revenue_sharing_basic.settings', 'revenue_sharing_basic_client_id_profile_field');
  config_clear('revenue_sharing_basic.settings', 'revenue_sharing_basic_percentage_author');
  config_clear('revenue_sharing_basic.settings', 'revenue_sharing_basic_percentage_refer');
  config_clear('revenue_sharing_basic.settings', 'revenue_sharing_basic_revenue_enable');
  $settings = db_query("SELECT name FROM {variable} WHERE name LIKE 'revenue\_sharing\_basic\_percentage\_role\_%'");
  foreach ($settings as $variable) {
    // TODO This variable was probably removed in Backdrop without replacement.
    variable_del($variable->name);
  }
  $settings = db_query("SELECT name FROM {variable} WHERE name LIKE 'revenue\_sharing\_basic\_node\_type\_%'");
  foreach ($settings as $variable) {
    // TODO This variable was probably removed in Backdrop without replacement.
    variable_del($variable->name);
  }
}

// TODO The old hook_update_N functions cannot be applied to Backdrop.
function revenue_sharing_basic_update_7100(&$sandbox) { }

/**
 * Implements hook_update_last_removed().
 */
function revenue_sharing_basic_update_last_removed() {
  return 7100;
}

/**
 * Migrate revenue_sharing_basic variables to config.
 */
function revenue_sharing_basic_update_1000() {
  $config = config('revenue_sharing_basic.settings');
  $config->set('revenue_sharing_basic_client_id_profile_field', update_variable_get('revenue_sharing_basic_client_id_profile_field', 'REVENUE_SHARING_BASIC_CLIENT_ID_PROFILE_FIELD_DEFAULT'));
  $config->set('revenue_sharing_basic_percentage_author', update_variable_get('revenue_sharing_basic_percentage_author', 'REVENUE_SHARING_BASIC_PERCENTAGE_AUTHOR_DEFAULT'));
  $config->set('revenue_sharing_basic_percentage_role_role', update_variable_get('revenue_sharing_basic_percentage_role_role', 'dynamic variable in file /adsense/old/revenue_sharing_basic/revenue_sharing_basic.module line 120'));
  $config->set('revenue_sharing_basic_percentage_refer', update_variable_get('revenue_sharing_basic_percentage_refer', 'REVENUE_SHARING_BASIC_PERCENTAGE_REFER_DEFAULT'));
  $config->set('revenue_sharing_basic_node_type_type', update_variable_get('revenue_sharing_basic_node_type_type', 'dynamic variable in file /adsense/old/revenue_sharing_basic/revenue_sharing_basic.admin.inc line 104'));
  $config->set('revenue_sharing_basic_node_type_infotype', update_variable_get('revenue_sharing_basic_node_type_infotype', 'dynamic variable in file /adsense/old/revenue_sharing_basic/revenue_sharing_basic.module line 112'));
  $config->save();

  update_variable_del('revenue_sharing_basic_client_id_profile_field');
  update_variable_del('revenue_sharing_basic_percentage_author');
  update_variable_del('revenue_sharing_basic_percentage_role_role');
  update_variable_del('revenue_sharing_basic_percentage_refer');
  update_variable_del('revenue_sharing_basic_node_type_type');
  update_variable_del('revenue_sharing_basic_node_type_infotype');
}

/**
 * Implements hook_install().
 */
function revenue_sharing_basic_install() {
  // Dynamically generated variable data was detected.
  // /adsense/old/revenue_sharing_basic/revenue_sharing_basic.module line 120
  // /adsense/old/revenue_sharing_basic/revenue_sharing_basic.admin.inc line 104
  // /adsense/old/revenue_sharing_basic/revenue_sharing_basic.module line 112
}
