<?php

/**
 * @file
 * Displays Google AdSense ads on Drupal pages.
 *
 * This is the core module of the AdSense package, with the Drupal hooks
 * and other administrative functions.
 */

/**
 * Implements hook_preprocess_block().
 */
function adsense_managed_preprocess_block(&$variables) {
  // Remove adsense from the block id and classes to bypass adblock rules.
  if (($variables['plugin_id'] == 'adsense_managed_ad_block') &&
      \Drupal::config('adsense.settings')->get('adsense_unblock_ads')) {
    $variables['attributes']['id'] = str_replace('adsense', '', $variables['attributes']['id']);
    $variables['configuration']['provider'] = str_replace('adsense', '', $variables['configuration']['provider']);
  }
}
